[package]
name         = "tinyone_ralloc"
version      = "0.2.0"
edition      = "2024"
description  = "Fixed-capacity arena allocator backing the TinyLang v1 runtime"
license-file = "../../LICENSE"
repository   = "https://github.com/ConnerAdamsMaine/TinyOne"

[lib]
name       = "ralloc"
path       = "src/lib.rs"
crate-type = [ "rlib", "cdylib", "staticlib" ]

[features]
default       = [ "rlib" ]
rlib          = [  ]
cdylib        = [  ]
c-staticlib   = [  ]
testing-hooks = [  ]

[dependencies]

[dev-dependencies]
tempfile             = "3"
static_assertions    = "1"
tinyone_test_support = { path = "../tinyone_test_support" }
