#ifndef TINYLANG_H
#define TINYLANG_H

#pragma once

/* Generated with cbindgen:0.29.2 */

/* Generated by cbindgen from the TinyLang C ABI. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#define TINYONE_ABI_VERSION 1u

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Return the declared stable TinyOne C ABI version.
 */
uint32_t tinyone_abi_version(void);

/**
 * # Safety
 *
 * `value` must be null or a pointer returned by a TinyOne C-ABI function
 * that has not already been freed.
 */
void tinyone_free_string(char *value);

/**
 * # Safety
 *
 * `source` must be non-null and point to a valid NUL-terminated UTF-8 C
 * string for the duration of the call and must be no larger than 1 MiB.
 * A null pointer or oversized string returns a compile error response.
 */
char *tinyone_lex_source_json(const char *source);

/**
 * # Safety
 *
 * `source` must be non-null and point to a valid NUL-terminated UTF-8 C
 * string for the duration of the call and must be no larger than 1 MiB.
 * A null pointer or oversized string returns a compile error response.
 */
char *tinyone_compile_source_json(const char *source);

/**
 * # Safety
 *
 * `path` must be non-null and point to a valid NUL-terminated UTF-8 C string
 * for the duration of the call and must be no larger than 32 KiB. A null
 * pointer or oversized string returns a compile error response.
 */
char *tinyone_compile_file_json(const char *path);

/**
 * # Safety
 *
 * `source` and `mode` must be non-null and point to valid NUL-terminated
 * UTF-8 C strings for the duration of the call. `source` is limited to 1 MiB
 * and `mode` to 16 bytes. `inputs_json` is nullable; null means an empty input
 * queue. A non-null `inputs_json` is limited to 8 MiB.
 */
char *tinyone_run_source_json(const char *source, const char *mode, const char *inputs_json);

/**
 * # Safety
 *
 * `path` and `mode` must be non-null and point to valid NUL-terminated UTF-8
 * C strings for the duration of the call. `path` is limited to 32 KiB and
 * `mode` to 16 bytes. `inputs_json` is nullable; null means an empty input
 * queue. A non-null `inputs_json` is limited to 8 MiB.
 */
char *tinyone_run_file_json(const char *path, const char *mode, const char *inputs_json);

/**
 * # Safety
 *
 * `artifact_json` and `mode` must be non-null and point to valid NUL-terminated
 * UTF-8 C strings for the duration of the call. `mode` is limited to 16 bytes.
 * `inputs_json` is nullable; null means an empty input queue. A non-null
 * `inputs_json` is limited to 8 MiB.
 * `artifact_json` must not exceed the documented artifact byte limit.
 * `mode` is limited to 16 bytes and `inputs_json` to 8 MiB.
 */
char *tinyone_run_artifact_json(const char *artifact_json,
                                const char *mode,
                                const char *inputs_json);

/**
 * # Safety
 *
 * `artifact_json` must be non-null and point to a valid NUL-terminated UTF-8
 * C string for the duration of the call. A null pointer returns a compile
 * error response. It must not exceed the documented artifact byte limit.
 */
char *tinyone_jit_listing_json(const char *artifact_json);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TINYLANG_H */
