#ifndef TINYLANG_H
#define TINYLANG_H

#pragma once

/* Generated with cbindgen:0.29.2 */

/* Generated by cbindgen from the TinyLang C ABI. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * # Safety
 *
 * `value` must be null or a pointer returned by a TinyOne C-ABI function
 * that has not already been freed.
 */
void tinyone_free_string(char *value);

/**
 * # Safety
 *
 * `source` may be null. If non-null, it must point to a valid
 * NUL-terminated UTF-8 C string for the duration of the call.
 */
char *tinyone_lex_source_json(const char *source);

/**
 * # Safety
 *
 * `source` may be null. If non-null, it must point to a valid
 * NUL-terminated UTF-8 C string for the duration of the call.
 */
char *tinyone_compile_source_json(const char *source);

/**
 * # Safety
 *
 * `path` may be null. If non-null, it must point to a valid NUL-terminated
 * UTF-8 C string for the duration of the call.
 */
char *tinyone_compile_file_json(const char *path);

/**
 * # Safety
 *
 * `source`, `mode`, and `inputs_json` may be null. Any non-null pointer must
 * point to a valid NUL-terminated UTF-8 C string for the duration of the call.
 */
char *tinyone_run_source_json(const char *source, const char *mode, const char *inputs_json);

/**
 * # Safety
 *
 * `path`, `mode`, and `inputs_json` may be null. Any non-null pointer must
 * point to a valid NUL-terminated UTF-8 C string for the duration of the call.
 */
char *tinyone_run_file_json(const char *path, const char *mode, const char *inputs_json);

/**
 * # Safety
 *
 * `artifact_json`, `mode`, and `inputs_json` may be null. Any non-null pointer
 * must point to a valid NUL-terminated UTF-8 C string for the duration of the
 * call. `artifact_json` must not exceed the documented artifact byte limit.
 */
char *tinyone_run_artifact_json(const char *artifact_json,
                                const char *mode,
                                const char *inputs_json);

/**
 * # Safety
 *
 * `artifact_json` may be null. If non-null, it must point to a valid
 * NUL-terminated UTF-8 C string for the duration of the call and must not
 * exceed the documented artifact byte limit.
 */
char *tinyone_jit_listing_json(const char *artifact_json);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TINYLANG_H */
