#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum TokenKind {
    Int,
    Ident,
    String,
    Let,
    Print,
    Fn,
    Return,
    While,
    If,
    Else,
    Break,
    Continue,
    Struct,
    Import,
    Export,
    As,
    Set,
    Unsafe,
    Plus,
    Minus,
    Star,
    Slash,
    Equal,
    EqEq,
    BangEqual,
    Lt,
    Lte,
    Gt,
    Gte,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Dot,
    Comma,
    Eof,
    Null,
}

impl TokenKind {
    pub(crate) fn name(self) -> &'static str {
        match self {
            TokenKind::Int => "INT",
            TokenKind::Ident => "IDENT",
            TokenKind::String => "STRING",
            TokenKind::Let => "LET",
            TokenKind::Print => "PRINT",
            TokenKind::Fn => "FN",
            TokenKind::Return => "RETURN",
            TokenKind::While => "WHILE",
            TokenKind::If => "IF",
            TokenKind::Else => "ELSE",
            TokenKind::Break => "BREAK",
            TokenKind::Continue => "CONTINUE",
            TokenKind::Struct => "STRUCT",
            TokenKind::Import => "IMPORT",
            TokenKind::Export => "EXPORT",
            TokenKind::As => "AS",
            TokenKind::Set => "SET",
            TokenKind::Unsafe => "UNSAFE",
            TokenKind::Plus => "PLUS",
            TokenKind::Minus => "MINUS",
            TokenKind::Star => "STAR",
            TokenKind::Slash => "SLASH",
            TokenKind::Equal => "EQUAL",
            TokenKind::EqEq => "EQEQ",
            TokenKind::BangEqual => "BANG_EQUAL",
            TokenKind::Lt => "LT",
            TokenKind::Lte => "LTE",
            TokenKind::Gt => "GT",
            TokenKind::Gte => "GTE",
            TokenKind::LParen => "LPAREN",
            TokenKind::RParen => "RPAREN",
            TokenKind::LBrace => "LBRACE",
            TokenKind::RBrace => "RBRACE",
            TokenKind::LBracket => "LBRACKET",
            TokenKind::RBracket => "RBRACKET",
            TokenKind::Dot => "DOT",
            TokenKind::Comma => "COMMA",
            TokenKind::Eof => "EOF",
            TokenKind::Null => "NULL",
        }
    }
}

#[derive(Debug, Clone)]
pub(crate) struct Token {
    pub(crate) kind: TokenKind,
    pub(crate) text: String,
    pub(crate) pos: usize,
    pub(crate) end: usize,
}
