use crate::{Result, TinyOneError};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Op {
    PushInt,
    Load,
    Store,
    Add,
    Sub,
    Mul,
    Div,
    Neg,
    Print,
    Lt,
    Lte,
    Gt,
    Gte,
    Eq,
    Ne,
    Jump,
    JumpIfZero,
    Call,
    Return,
    Halt,
    PushString,
    MakeArray,
    Index,
    SetIndex,
    MakeStruct,
    GetField,
    SetField,
    Builtin,
    PushNull,
    Pop,
    LoadGlobal,
}

impl Op {
    pub(crate) fn name(self) -> &'static str {
        match self {
            Op::PushInt => "PUSH_INT",
            Op::Load => "LOAD",
            Op::Store => "STORE",
            Op::Add => "ADD",
            Op::Sub => "SUB",
            Op::Mul => "MUL",
            Op::Div => "DIV",
            Op::Neg => "NEG",
            Op::Print => "PRINT",
            Op::Lt => "LT",
            Op::Lte => "LTE",
            Op::Gt => "GT",
            Op::Gte => "GTE",
            Op::Eq => "EQ",
            Op::Ne => "NE",
            Op::Jump => "JUMP",
            Op::JumpIfZero => "JUMP_IF_ZERO",
            Op::Call => "CALL",
            Op::Return => "RETURN",
            Op::Halt => "HALT",
            Op::PushString => "PUSH_STRING",
            Op::MakeArray => "MAKE_ARRAY",
            Op::Index => "INDEX",
            Op::SetIndex => "SET_INDEX",
            Op::MakeStruct => "MAKE_STRUCT",
            Op::GetField => "GET_FIELD",
            Op::SetField => "SET_FIELD",
            Op::Builtin => "BUILTIN",
            Op::PushNull => "PUSH_NULL",
            Op::Pop => "POP",
            Op::LoadGlobal => "LOAD_GLOBAL",
        }
    }

    pub(crate) fn from_name(name: &str) -> Result<Self> {
        Ok(match name {
            "PUSH_INT" => Op::PushInt,
            "LOAD" => Op::Load,
            "STORE" => Op::Store,
            "ADD" => Op::Add,
            "SUB" => Op::Sub,
            "MUL" => Op::Mul,
            "DIV" => Op::Div,
            "NEG" => Op::Neg,
            "PRINT" => Op::Print,
            "LT" => Op::Lt,
            "LTE" => Op::Lte,
            "GT" => Op::Gt,
            "GTE" => Op::Gte,
            "EQ" => Op::Eq,
            "NE" => Op::Ne,
            "JUMP" => Op::Jump,
            "JUMP_IF_ZERO" => Op::JumpIfZero,
            "CALL" => Op::Call,
            "RETURN" => Op::Return,
            "HALT" => Op::Halt,
            "PUSH_STRING" => Op::PushString,
            "MAKE_ARRAY" => Op::MakeArray,
            "INDEX" => Op::Index,
            "SET_INDEX" => Op::SetIndex,
            "MAKE_STRUCT" => Op::MakeStruct,
            "GET_FIELD" => Op::GetField,
            "SET_FIELD" => Op::SetField,
            "BUILTIN" => Op::Builtin,
            "PUSH_NULL" => Op::PushNull,
            "POP" => Op::Pop,
            "LOAD_GLOBAL" => Op::LoadGlobal,
            _ => return Err(TinyOneError::compile(format!("Unknown opcode {name:?}"))),
        })
    }

    pub(crate) fn ordinal(self) -> u16 {
        match self {
            Op::PushInt => 1,
            Op::Load => 2,
            Op::Store => 3,
            Op::Add => 4,
            Op::Sub => 5,
            Op::Mul => 6,
            Op::Div => 7,
            Op::Neg => 8,
            Op::Print => 9,
            Op::Lt => 10,
            Op::Lte => 11,
            Op::Gt => 12,
            Op::Gte => 13,
            Op::Eq => 14,
            Op::Ne => 15,
            Op::Jump => 16,
            Op::JumpIfZero => 17,
            Op::Call => 18,
            Op::Return => 19,
            Op::Halt => 20,
            Op::PushString => 21,
            Op::MakeArray => 22,
            Op::Index => 23,
            Op::SetIndex => 24,
            Op::MakeStruct => 25,
            Op::GetField => 26,
            Op::SetField => 27,
            Op::Builtin => 28,
            Op::PushNull => 29,
            Op::Pop => 30,
            Op::LoadGlobal => 31,
        }
    }
}
