[package]
name = "ralloc-staticlib"
version = "0.1.0"
edition = "2024"
publish = false
description = "Internal TinyLang Ralloc static-library wrapper"
license-file = "../../License.rst"
repository = "https://github.com/ConnerAdamsMaine/TinyOne"

[lib]
name = "ralloc"
path = "src/lib.rs"
crate-type = ["staticlib"]
test = false
doctest = false

[dependencies]
ralloc_core = { package = "ralloc", version = "0.2.0", path = ".." }
